replicaCount: 1

sshapp:
  enabled: true
  name: rda-webserver-test
  volume:
    fs:
      name: gdexdata
      mountPath: /data
    glade:
      name: glade-campaign
      server: gladedm1.ucar.edu
      path: /gpfs/csfs1
      mountPath: /glade/campaign
      readOnly: true
  container:
    image: 
      repository: lscr.io/linuxserver/openssh-server
      tag: latest
    port: 2222
    memory: 1G
    cpu: 2
  secret:
    path: dattore@ucar.edu/ssh_container
    usernameKey: username
    passwordKey: password
