replicaCount: 1

webapp:
  name: rda-webserver-test
  group: rda-web-test
  path: /
  tls:
    fqdn: rda-web-test.k8s.ucar.edu
    secretName: incommon-cert-rda-web-test
  container: 
    image: docker.io/dattore/rda-web-test:v3
    port: 8080
    memory: 1G
    cpu: 2

sshapp:
  enabled: true
  name: rda-sshserver-test
  group: rda-ssh-test
  container:
    image: docker.io/dattore/ssh-test:v10
    port: 2222
    memory: 1G
    cpu: 2

volume:
  fs:
    name: gdexdata
    mountPath: /data
  glade:
    name: glade-campaign
    server: gladedm1.ucar.edu
    path: /gpfs/csfs1
    mountPath: /glade/campaign
    readOnly: true
