replicaCount: 1

webapp:
  name: rda-webserver-test
  group: rda-web-test
  path: /
  tls:
    fqdn: rda-web-test.k8s.ucar.edu
    secretName: incommon-cert-rda-web-test
  volume:
    fs:
      name: gdexdata
      size: 55Gi
      mountPath: /data
    glade:
      name: glade-home
      server: gladedm1.ucar.edu
      path: /gpfs/u/home/rdadata
      mountPath: /glade/u/home/rdadata
      readOnly: true
  container: 
    image: docker.io/dattore/rda-web-test:v2
    port: 8080
    memory: 1G
    cpu: 2

sshapp:
  enabled: true
  name: rda-sshserver-test
  group: rda-ssh-test
  volume:
    fs:
      name: gdexdata
      size: 55Gi
      mountPath: /data
    glade:
      name: glade-campaign
      server: gladedm1.ucar.edu
      path: /gpfs/csfs1
      mountPath: /glade/campaign
      readOnly: true
  container:
    image: 
      repository: docker.io/dattore/ssh-test
      tag: latest
    port: 2222
    memory: 1G
    cpu: 2

volume:
  fs:
    name: gdexdata
    size: 55Gi
    mountPath: /data
  glade:
    name: glade-campaign
    server: gladedm1.ucar.edu
    path: /gpfs/csfs1
    mountPath: /glade/campaign
    readOnly: true
