replicaCount: 1

sshapp:
  enabled: true
  name: rda-ssh-test
  volume:
    fs:
      name: gdexdata
      size: 55Gi
      mountPath: /data
    glade:
      name: glade-campaign
      server: gladedm1.ucar.edu
      path: /gpfs/csfs1
      mountPath: /glade/campaign
      readOnly: true
  container:
    image: 
      repository: docker.io/dattore/ssh-test
      tag: latest
    port: 2222
    memory: 2G
    cpu: 2
  #secret:
  #  path: dattore@ucar.edu/ssh_container
  #  usernameKey: username
  #  passwordKey: password
