replicaCount: 1

webapp:
  name: rda-webserver-test
  group: rda-web-test
  path: /
  tls:
    fqdn: rda-web-test.k8s.ucar.edu
    secretName: incommon-cert-rda-web-test
  volume:
    fs:
      name: gdexdata
      size: 50Gi
      mountPath: /data
  container: 
    image: docker.io/dattore/rda-web-test:v19
    port: 8080
    memory: 1G
    cpu: 2
