replicaCount: 1

webapp:
  name: gaas
  group: gaas
  path: /
  tls:
    fqdn: gaas.k8s.ucar.edu
    secretName: incommon-cert-gaas
  container: 
    image: docker.io/dattore/rda-web-test:v3
    port: 8080
    memory: 1G
    cpu: 2

sshapp:
  enabled: false
  name: rda-sshserver-test
  group: rda-ssh-test
  container:
    image: docker.io/dattore/ssh-test:v10
    port: 2222
    memory: 1G
    cpu: 2

volume:
  fs:
    name: gaasdata
    size: 500Gi
    mountPath: /data
  glade:
    name: glade-campaign
    server: gladedm1.ucar.edu
    path: /gpfs/csfs1
    mountPath: /glade/campaign
    readOnly: true
