on:
  push:
    paths:
      - "myweb/**"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the latest image
        run: docker pull dattore/rda-web-test:latest
      - name: Get the latest version number
        run: docker run dattore/rda-web-test /bin/bash -c '/usr/local/bin/get_version'
