on:
  push:
    paths-ignore:
      - ".github/**"

jobs:
  container-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the latest image
        run: docker pull dattore/rda-web-test:latest
      - name: Get the latest version number
        run: echo "VERSION=$(docker run dattore/rda-web-test /bin/bash -c '/usr/local/bin/get_version' | cut -c2,10)" >> $GITHUB_ENV
      - name: Increment version number
        run: ((VERSION++))
      - name: Create new version tag
        run: VERSION="v"$VERSION
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Junk step
        run: |
          export A=a
          export B=b
          export C=${{ secrets.MY_SECRET }}
          echo "$A $B $C"
