on:
  push:
    paths-ignore:
      - ".github/**"
      - "app-chart/**"

jobs:
  container-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the latest image
        run: docker pull dattore/rda-web-test:latest
      - name: Get the latest version number
        run: echo "VERSION=$(docker run dattore/rda-web-test /bin/bash -c '/usr/local/bin/get_version' | cut -c2,10)" >> $GITHUB_ENV
      - name: Increment version number
        run: ((VERSION++))
      - name: Create new version tag
        run: VERSION="v"$VERSION
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Export secrets
        run: |
          export WAGTAIL_USERNAME=${{ secrets.WAGTAIL_USERNAME }}
          export WAGTAIL_PASSWORD=${{ secrets.WAGTAIL_PASSWORD }}
          export WAGTAIL_HOST=${{ secrets.WAGTAIL_HOST }}
          export WAGTAIL_DBNAME=${{ secrets.WAGTAIL_DBNAME }}
          export WAGTAIL_PORT=${{ secrets.WAGTAIL_PORT }}
          export DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}
          export DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}
          export DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL}}
      - name: Build new version of the container
        run: >
          docker build --platform linux/amd64 --build-arg VERSION=$VERSION
          --secret id=WAGTAIL_USERNAME --secret id=WAGTAIL_PASSWORD
          --secret id=WAGTAIL_HOST --secret id=WAGTAIL_PORT --secret id=WAGTAIL_DBNAME
          --secret id=DJANGO_SUPERUSER_USERNAME --secret id=DJANGO_SUPERUSER_PASSWORD
          --secret id=DJANGO_SUPERUSER_EMAIL -t dattore/rda-web-test:$VERSION --no-cache .
