on:
  push:
    paths-ignore:
      - ".github/**"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the latest image
        run: docker pull dattore/rda-web-test:latest
      - name: Get the latest version number
        run: echo "VERSION=$(docker run dattore/rda-web-test /bin/bash -c '/usr/local/bin/get_version')" >> $GITHUB_ENV
      - name: Print version
        run: echo $VERSION
