on:
  push:
    paths-ignore:
      - ".github/**"
      - "app-chart/**"

jobs:
  container-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull the latest image
        run: docker pull dattore/rda-web-test:latest
      - name: Get the latest version number
        id: last_version_number
        run: echo "VERSION_NUMBER=$(docker run dattore/rda-web-test /bin/bash -c '/usr/local/bin/get_version_number')" >> $GITHUB_OUTPUT
      - name: Increment version number
        id: new_version_number
        run: echo "VERSION_NUMBER=$((${{ steps.last_version_number.outputs.VERSION_NUMBER }}+1))" >> $GITHUB_OUTPUT
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Export secrets
        id: secrets
        run: |
          echo "WAGTAIL_USERNAME=${{ secrets.WAGTAIL_USERNAME }}" >> $GITHUB_ENV
          echo "WAGTAIL_PASSWORD=${{ secrets.WAGTAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "WAGTAIL_HOST=${{ secrets.WAGTAIL_HOST }}" >> $GITHUB_ENV
          echo "WAGTAIL_DBNAME=${{ secrets.WAGTAIL_DBNAME }}" >> $GITHUB_ENV
          echo "WAGTAIL_PORT=${{ secrets.WAGTAIL_PORT }}" >> $GITHUB_ENV
          echo "DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }}" >> $GITHUB_ENV
          echo "DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }}" >> $GITHUB_ENV
          echo "DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL}}" >> $GITHUB_ENV
      - name: Build new version of the container
        run: >
          docker build --platform linux/amd64
          --build-arg VERSION_NUMBER=${{ steps.new_version_number.outputs.VERSION_NUMBER }}
          --secret id=WAGTAIL_USERNAME --secret id=WAGTAIL_PASSWORD
          --secret id=WAGTAIL_HOST --secret id=WAGTAIL_PORT --secret id=WAGTAIL_DBNAME
          --secret id=DJANGO_SUPERUSER_USERNAME --secret id=DJANGO_SUPERUSER_PASSWORD
          --secret id=DJANGO_SUPERUSER_EMAIL
          -t dattore/rda-web-test:v${{ steps.new_version_number.outputs.VERSION_NUMBER }}
          --no-cache .
      - name: Push the new image to Docker Hub
        run: docker push dattore/rda-web-test:v${{ steps.new_version_number.outputs.VERSION_NUMBER }}
      - name: Copy the new image to "latest"
        run: docker tag dattore/rda-web-test:v${{ steps.new_version_number.outputs.VERSION_NUMBER}} dattore/rda-web-test:latest
      - name: Push "latest" to Docker Hub
        run: docker push dattore/rda-web-test:latest
