on:
  push

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the latest image
        run: docker pull dattore/rda-web-test:latest
      - name: Get the latest version number
        run: version=`docker run dattore/rda-web-test /bin/bash -c '/usr/local/bin/get_version'`
      - name: Print the version number
        run: echo $version
