on:
  push:
    paths-ignore:
      - ".github/**"
      - "app-chart/**"

jobs:
  container-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update Chart.yaml
        run: |
          git status
          sed "s/0.1.2/0.1.3/" app-chart/Chart.yaml > app-chart/Chart.yaml.new
          ls app-chart/
          mv app-chart/Chart.yaml.new app-chart/Chart.yaml
          ls app-chart/
          git status
          git add app-chart/Chart.yaml
          git commit -m "increment version"
          git status
          git push
